### ISSUE TITLE
Can't see the content of HomeScreen 

### ISSUE THREAD

**Issue by Pranav108** [Saransh-cpp/BookRentApp-Chapter3#39] opened 2021-12-05 15:40 UTC
For many of us we can't see the content of HomeScreen due to error with SingleChildScrollView (because it is encapsulating  AppBar, Drawer, Body etc.).
Though the app is running even with this issue.
As a result we may see some error like this:
![renderScreenError](https://user-images.githubusercontent.com/56934594/144753265-c4320994-d522-411e-84c3-6e9fb3409de7.png)

**Comment by Saransh-cpp** [comment] 2021-12-05 16:14
Root cause - #23 

Would you like to work on this?

**Comment by Saransh-cpp** [comment] 2021-12-05 16:25
@all-contributors please add @Pranav108 for bug

**Comment by Pranav108** [comment] 2021-12-05 16:34
> Root cause - #23
> 
> Would you like to work on this?

This question is not for me , right?

**Comment by Saransh-cpp** [comment] 2021-12-05 20:05
> > Root cause - #23
> > Would you like to work on this?
> 
> This question is not for me , right?

Oh, my bad. This has already been fixed in #26.

**Closed** 2021-12-06 06:22 UTC
Labels: good first issue, CodePeak, SWoC
